In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as mypd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score
from sklearn import metrics
from sklearn.model_selection import train_test_split



In [2]:
mydata=mypd.read_csv("Iris_data.csv")

In [4]:
mydata.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           1           5.1          3.5           1.4          0.2        0
1           2           4.9          3.0           1.4          0.2        0
2           3           4.7          3.2           1.3          0.2        0
3           4           4.6          3.1           1.5          0.2        0
4           5           5.0          3.6           1.4          0.2        0

In [7]:
x=mydata.iloc[:,:4].values
x

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  7. ,   4.6,   3.4,   1.4],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 29. ,   5.2,   3.4,   1.4],
       [ 32. ,   5.4,   3.4,   1.5],
       [ 33. ,   5.2,   4.1,   1.5],
       [ 35. ,   4.9,   3.1,   1.5],
       [ 36. ,   5. ,   3.2,   1.2],
       [ 37. ,   5.5,   3.5,   1.3],
       [ 38. ,   4.9,   3.6,   1.4],
       [ 39. ,   4.4,   3. ,   1.3],
       [ 42. ,   4.5,   2.3,   1.3],
 

In [10]:
y=mydata['Species'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [19]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [21]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 0, 2, 0, 0, 0, 2, 1])

In [23]:
cm=confusion_matrix(y_test,y_pred)
print("Accuracy:",accuracy_score(y_test,y_pred))
cm


Accuracy: 1.0


array([[10,  0,  0],
       [ 0,  8,  0],
       [ 0,  0,  3]])

In [26]:
print(metrics.classification_report(y_test,classifier.predict(x_test)))
      

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         3

    accuracy                           1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21



In [27]:
df=mypd.DataFrame({'Real Values':y_test,'predicted values':y_pred})
df

Real Values  predicted values
0             1                 1
1             0                 0
2             1                 1
3             1                 1
4             0                 0
5             0                 0
6             0                 0
7             0                 0
8             1                 1
9             1                 1
10            1                 1
11            1                 1
12            0                 0
13            2                 2
14            0                 0
15            2                 2
16            0                 0
17            0                 0
18            0                 0
19            2                 2
20            1                 1